In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.__version__

'1.4.2'

In [3]:
pwd

'C:\\Users\\Ebenezer\\Documents\\33985574-UNZIP-FOR-NOTEBOOKS-FINAL\\03-Pandas'

In [4]:
df = pd.read_csv('housing.csv')

In [5]:
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [8]:
len(df.columns)

10

In [14]:
df.dropna(axis=1)

longitude  latitude  housing_median_age  total_rooms  population  \
0        -122.23     37.88                41.0        880.0       322.0   
1        -122.22     37.86                21.0       7099.0      2401.0   
2        -122.24     37.85                52.0       1467.0       496.0   
3        -122.25     37.85                52.0       1274.0       558.0   
4        -122.25     37.85                52.0       1627.0       565.0   
...          ...       ...                 ...          ...         ...   
20635    -121.09     39.48                25.0       1665.0       845.0   
20636    -121.21     39.49                18.0        697.0       356.0   
20637    -121.22     39.43                17.0       2254.0      1007.0   
20638    -121.32     39.43                18.0       1860.0       741.0   
20639    -121.24     39.37                16.0       2785.0      1387.0   

       households  median_income  median_house_value ocean_proximity  
0           126.0         8.3252            452600.0        NEAR BAY  
1          1138.0         8.3014            358500.0        NEAR BAY  
2           177.0         7.2574            352100.0        NEAR BAY  
3           219.0         5.6431            341300.0        NEAR BAY  
4           259.0         3.8462            342200.0        NEAR BAY  
...           ...            ...                 ...             ...  
20635       330.0         1.5603             78100.0          INLAND  
20636       114.0         2.5568             77100.0          INLAND  
20637       433.0         1.7000             92300.0          INLAND  
20638       349.0         1.8672             84700.0          INLAND  
20639       530.0         2.3886             89400.0          INLAND  

[20640 rows x 9 columns]

In [15]:
df['ocean_proximity'].nunique()

5

In [22]:
df.groupby('ocean_proximity').mean().transpose()

ocean_proximity         <1H OCEAN         INLAND        ISLAND       NEAR BAY  \
longitude             -118.847766    -119.732990    -118.35400    -122.260694   
latitude                34.560577      36.731829      33.35800      37.801057   
housing_median_age      29.279225      24.271867      42.40000      37.730131   
total_rooms           2628.343586    2717.742787    1574.60000    2493.589520   
total_bedrooms         546.539185     533.881619     420.40000     514.182819   
population            1520.290499    1391.046252     668.00000    1230.317467   
households             517.744965     477.447565     276.60000     488.616157   
median_income            4.230682       3.208996       2.74442       4.172885   
median_house_value  240084.285464  124805.392001  380440.00000  259212.311790   

ocean_proximity        NEAR OCEAN  
longitude             -119.332555  
latitude                34.738439  
housing_median_age      29.347254  
total_rooms           2583.700903  
total_bedrooms         538.615677  
population            1354.008653  
households             501.244545  
median_income            4.005785  
median_house_value  249433.977427

In [23]:
df['total_bedrooms'].mean()

537.8705525375618

In [26]:
(df['total_bedrooms'].fillna(value=df['total_bedrooms'].mean())).mean()

537.8705525375639

In [28]:
a = df[df['ocean_proximity'] == 'ISLAND']

In [32]:
x = (a[['housing_median_age','total_rooms','total_bedrooms']]).to_numpy()

In [33]:
x

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [52]:
c = x.transpose()
c

array([[  27.,   52.,   52.,   52.,   29.],
       [1675., 2359., 2127.,  996.,  716.],
       [ 521.,  591.,  512.,  264.,  214.]])

In [59]:
b = np.matmul(c,x)

b = np.linalg.inv(b)
b

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [60]:
y = [950, 1300, 800, 1000, 1300]

In [61]:
d = np.matmul(b,c)

In [62]:
np.matmul(d,y)

array([23.12330961, -1.48124183,  5.69922946])